---
- hosts: localhost
  vars:
    target: cacao
  vars_files:
  - roles/secret/files/gruyere
  - roles/secret/files/bat
  roles:
  - secret
  - dotfiles
  - common
  tasks:
  - include_role:
      name: desktop
    when: ansible_user_id != 'root'
  - include_role:
      name: sync-configuration
    vars:
      make_target: cacao
