---
- hosts: localhost
  vars_files:
  - roles/secret/files/gruyere
  roles:
  - secret
  - dotfiles
  - common
  - { role: dev-env }
  - desktop
  tasks:
  - include_role:
      name: sync-configuration
    vars:
      make_target: hops

