---
- hosts: localhost
  roles:
  - { role: packages, become: true }
  - secret
  - dotfiles
    # - { role: dev-env }
  - weechat-role
  tasks:
  - include_role:
      name: sync-configuration
    vars:
      make_target: jahoda

