---
- hosts: localhost
  vars:
    target: jahoda
  vars_files:
  - roles/secret/files/gruyere
  roles:
  - { role: packages, become: true }
  - secret
  - dotfiles
  - common
  tasks:
  - include_role:
      name: sync-configuration
  - include_role:
      name: weechat-role
    vars:
      connect_to_server: redhat
