---
- hosts: localhost
  vars_files:
  - roles/secret/files/gruyere
  roles:
  - { role: packages, become: true }
  - secret
  - dotfiles
  - common
    # - { role: dev-env }
  tasks:
  - include_role:
      name: sync-configuration
    vars:
      make_target: jahoda
  - include_role:
      name: weechat-role
    vars:
      connect_to_server: redhat
