# TODO: run this playbook daily - s/sync-dotfiles/sync-configuration/
---
- hosts: localhost
  roles:
  - { role: packages, tags: ['core', 'graphical', 'workstation'], become: true }
  - secret
  - dotfiles
  tasks:
  - include_role:
      name: sync-configuration
    vars:
      playbook: oat.yaml

