---
- hosts: localhost
  vars_files:
  - roles/secret/files/gruyere
  - roles/secret/files/bat
  roles:
  - { role: packages, become: true }
  - secret
  - dotfiles
  - common
  - { role: dev-env }
  tasks:
  - include_role:
      name: desktop
    when: ansible_user != root
  - include_role:
      name: redhat-internal-ansible-role
  - include_role:
      name: sync-configuration
    vars:
      make_target: oat
