---
- hosts: localhost
  vars_files:
  - roles/secret/files/gruyere
  roles:
  - { role: packages, become: true }
  - secret
  - dotfiles
  - common
  - { role: dev-env }
  tasks:
  - include_role:
      name: sync-configuration
    vars:
      make_target: soy
  - hostname:
      name: soy

