---
- hosts: localhost
  roles:
  - { role: packages, become: true }
  - secret
  - dotfiles
  tasks:
  - include_role:
      name: sync-configuration
    vars:
      make_target: soy
  - hostname:
      name: soy

