---
- name: install core packages
  dnf:
    state: latest
    name:
    - NetworkManager-tui
    - ansible
    - at
    - autojump
    - autojump-zsh
    - copr-cli
    - cyrus-sasl-gssapi
    - fedora-packager
    - fedpkg
    - git
    - glances
    - gnupg
    - htop
    - iotop
    - less
    - lm_sensors
    - lshw
    - mc
    - mosh
    - powertop
    - pretty-git-prompt
    - python3-firewall
    - python3-PyGithub
    - python3-docker
    - python3-ipdb
    - python3-tabulate
    - python3-policycoreutils
    - rsync
    - sen
    - smartmontools
    - stow
    - strace
    - sudo
    - tig
    - tmux
    - tmux-top
    - tree
    - vim
    - zsh
- name: install workstation packages
  dnf:
    state: latest
    name:
    - asciinema
    - buildah
    - byzanz
    - cri-o
    - distgen
    - fedora-review
    - flatpak-builder
    - golang-github-cpuguy83-go-md2man
    - iwl7260-firmware
    - origin
    - pyp2rpm
    - rebase-helper
    - runc
    - rust
    - source-to-image
  tags:
    - workstation
- name: enable Petove pycharm copr repo
  command: dnf copr enable -y phracek/PyCharm
  args:
    warn: false
  tags:
    - workstation

- name: install rpm fusion
  dnf:
    state: present
    name:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
  tags:
    - workstation

- name: install graphical packages
  dnf:
    state: latest
    name:
    - NetworkManager-openvpn-gnome
    - abattis-cantarell-fonts
      # - avidemux
    - baobab
    - clearlooks-phenix-gtk2-theme
    - clearlooks-phenix-gtk3-theme
    - clearlooks-phenix-xfwm4-theme
      # - darktable
    - evince
    - file-roller
    - geeqie
    # - gimp  # use flatpak instead
    - google-droid-kufi-fonts
    - google-droid-sans-fonts
    - google-droid-sans-mono-fonts
    - google-droid-serif-fonts
    - google-roboto-fonts
    - gparted
    - gvfs-mtp
    - levien-inconsolata-fonts
      # - mscore-fonts
    - neovim
    - nextcloud-client
    # - obs-studio
    - orage
    - pavucontrol
    - pycharm-community
    - pycharm-community-plugins
    - sxiv
    - vagrant-libvirt
    - vagrant-sshfs
    - virt-manager
    # - wine
    # - wine-core
    # - wine-tahoma-fonts-system
    # - wine-times-new-roman-fonts-system
    # - wine-wingdings-fonts-system
    - xclip
    - xfce4-clipman-plugin
    - xfce4-cpugraph-plugin
    - xfce4-weather-plugin
    - xfce4-xkb-plugin
    - xorg-x11-drv-evdev
    - xorg-x11-drv-fbdev
    - xorg-x11-drv-libinput
    - xorg-x11-drv-vesa
    - xorg-x11-utils
  tags:
    - graphical
- name: enable flathub
  command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - graphical
- name: install flatpaks
  command: flatpak install -y {{ item }}
  with_items:
  - flathub org.videolan.VLC
  tags:
    - graphical
- name: update flatpaks
  command: flatpak update -y
  tags:
    - graphical
