---
- name: install core packages
  dnf:
    state: latest
    name:
    - NetworkManager-tui
    - ansible-core
    - autojump
    - autojump-zsh
    - fedora-packager
    - fedpkg
    - git-core
    - gnupg
    - htop
    - less
    - lm_sensors
    - lshw
    - mc
    - mosh
    - pretty-git-prompt
    - python3-PyGithub
    - python3-tabulate
    - rsync
    # - sen  # not in EPEL
    - smartmontools
    - strace
    - sudo
    - tig
    - tmux
    # - tmux-top  # not in EPEL
    - tree
    - neovim
    - zsh

- name: enable copr repos
  tags:
    - graphical
  command: dnf copr enable -y {{ item }}
  with_items:
  - peterwu/iosevka

- name: add google-chrome repo
  tags:
    - graphical
  copy:
    src: '{{ role_path }}/files/google-chrome.repo'
    dest: /etc/yum.repos.d/google-chrome.repo

- name: install rpm fusion
  dnf:
    state: present
    name:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_version'] }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_version'] }}.noarch.rpm
    disable_gpg_check: true
  tags:
    - graphical
  ignore_errors: true

- name: install graphical packages
  dnf:
    state: latest
    name:
    - abattis-cantarell-fonts
    - iosevka-fonts  # in a copr repo
    - evince
    - geeqie
    - google-droid-sans-fonts
    - google-droid-sans-mono-fonts
    - google-droid-serif-fonts
    - google-roboto-fonts
    - gvfs-mtp
    - levien-inconsolata-fonts
    - xclip
    - google-chrome-stable
  tags:
    - graphical

- name: enable flathub
  command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - graphical

- name: install flatpaks
  command: flatpak install -y {{ item }}
  with_items:
  - flathub org.videolan.VLC
  - flathub com.obsproject.Studio
  - flathub org.gimp.GIMP
  - flathub org.kde.kdenlive
  - flathub org.libreoffice.LibreOffice
  tags:
    - graphical

- name: update flatpaks
  command: flatpak update -y
  tags:
    - graphical
