---
- name: install core packages
  dnf:
    state: latest
    name:
    - NetworkManager-tui
    - ansible
    - at
    - autojump
    - autojump-zsh
    - copr-cli
    - cyrus-sasl-gssapi
    - fedora-packager
    - fedpkg
    - git
    - glances
    - gnupg
    - htop
    - iotop
    - less
    - lm_sensors
    - lshw
    - mc
    - mosh
    - powertop
    - pretty-git-prompt
    - python3-firewall
    - python3-PyGithub
    - python3-docker
    - python3-ipdb
    - python3-tabulate
    - python3-policycoreutils
    - rsync
    - sen
    - smartmontools
    - stow
    - strace
    - sudo
    - tig
    - tmux
    - tmux-top
    - tree
    - vim
    - zsh

- name: enable copr repos
  tags:
    - workstation
  command: dnf copr enable -y {{ item }}
  with_items:
  - peterwu/iosevka

- name: install rpm fusion
  dnf:
    state: present
    name:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
  tags:
    - workstation
  ignore_errors: true

- name: install graphical packages
  dnf:
    state: latest
    name:
    - abattis-cantarell-fonts
    - iosevka-fonts  # in a copr repo
    - evince
    - geeqie
    - google-droid-sans-fonts
    - google-droid-sans-mono-fonts
    - google-droid-serif-fonts
    - google-roboto-fonts
    - gvfs-mtp
    - levien-inconsolata-fonts
    - neovim
    - nextcloud-client
    - pycharm-community
    - pycharm-community-plugins
    - xclip
  tags:
    - workstation

- name: enable flathub
  command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - graphical

- name: install flatpaks
  command: flatpak install -y {{ item }}
  with_items:
  - flathub org.videolan.VLC
  - flathub com.obsproject.Studio
  - flathub com.slack.Slack
  - flathub com.spotify.Client
  - flathub im.riot.Riot
  - flathub org.gimp.GIMP
  - flathub org.kde.kdenlive
  - flathub org.libreoffice.LibreOffice
  - flathub org.videolan.VLC
  tags:
    - graphical

- name: update flatpaks
  command: flatpak update -y
  tags:
    - graphical
