---
- name: clone repository with dotfiles
  git:
    repo: git@github.com:TomasTomecek/dotfiles
    dest: ~/.dotfiles
    recursive: yes
    accept_hostkey: yes
    update: yes
  ignore_errors: yes
# TODO: use ansible instead of stow
- name: symlink dotfiles
  command: stow tmux zsh vim git p-g-p
  args:
    chdir: ~/.dotfiles
- name: create dir for nvim
  file:
    dest: ~/.config/nvim/
    state: directory
- name: create dir for mc
  file:
    dest: ~/.config/mc/
    state: directory
- name: symlink mc.keymap
  file:
    state: link
    dest: ~/.config/mc/mc.keymap
    src: ~/.dotfiles/mc/mc.keymap
- name: prep for nvim
  copy:
    dest: ~/.config/nvim/init.vim
    content: |
          set runtimepath^=~/.vim runtimepath+=~/.vim/after
          let &packpath = &runtimepath
          source ~/.vimrc
- name: create dirs in .vim
  file:
    dest: '{{ item }}'
    state: directory
  with_items:
  - ~/.vim/autoload
  - ~/.vim/indent
- name: 'vim: copy indent file for yaml'
  copy:
    src: yaml.vim
    dest: ~/.vim/indent/
- name: initialize vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
  # FIXME: https://stackoverflow.com/questions/33672491/how-to-use-ansible-to-provision-vim-vundle-plugin
- name: manually install vim-plug
  debug:
    msg: 'run in shell: "vim +PlugInstall"'
# TODO: services role: open firewall 60001 port for mosh, change ssh port, disable root login
