---
- name: inspect ~/.dotfiles dir
  stat:
    path: ~/.dotfiles
  register: dotfiles_path
- name: clone repository with dotfiles
  git:
    repo: https://github.com/TomasTomecek/dotfiles
    dest: ~/.dotfiles
    track_submodules: yes
    recursive: yes
    accept_hostkey: yes
  when: not dotfiles_path.stat.exists
# TODO: use ansible instead of stow
- name: symlink dotfiles
  command: stow tmux zsh vim git
  args:
    chdir: ~/.dotfiles
- name: create .vim/autoload dir
  file:
    dest: ~/.vim/autoload
    state: directory
- name: initialize vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
# TODO: run as headless
# - name: install vim plugins
#   command: vim +PlugInstall
# TODO: services role: open firewall 60001 port for mosh, change ssh port, disable root login
