---
- name: clone repository with dotfiles
  git:
    repo: git@github.com:TomasTomecek/dotfiles
    dest: ~/.dotfiles
    track_submodules: yes
    recursive: yes
    accept_hostkey: yes
    update: yes
  register: command_result
  failed_when: "command_result.failed and 'Local modifications exist in repository' not in command_result.msg"
# - debug:
#     msg: '{{ command_result }}'
# TODO: use ansible instead of stow
- name: symlink dotfiles
  command: stow tmux zsh vim git p-g-p
  args:
    chdir: ~/.dotfiles
- name: create .vim/autoload dir
  file:
    dest: ~/.vim/autoload
    state: directory
- name: initialize vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
# TODO: run as headless
# - name: install vim plugins
#   command: vim +PlugInstall
# TODO: services role: open firewall 60001 port for mosh, change ssh port, disable root login
