---
- name: inspect ~/.dotfiles dir
  stat:
    path: ~/.dotfiles
  register: dotfiles_path
- name: clone repository with dotfiles
  git:
    repo: https://github.com/TomasTomecek/dotfiles
    dest: ~/.dotfiles
    track_submodules: yes
    recursive: yes
    accept_hostkey: yes
  when: not dotfiles_path.stat.exists
# TODO: use ansible instead of stow
- name: symlink dotfiles
  command: stow tmux zsh vim git
  args:
    chdir: ~/.dotfiles
# TODO: since I dont use vundle anymore, initiate vim
# TODO: services role: open firewall 60001 port for mosh, change ssh port, disable root login
