---
- name: clone repository with dotfiles
  git:
    repo: git@github.com:TomasTomecek/dotfiles
    dest: ~/.dotfiles
    recursive: yes
    accept_hostkey: yes
    update: yes
  ignore_errors: yes
- name: create dirs for dotfiles
  file:
    dest: '{{ item }}'
    state: directory
  loop:
  - ~/.config
  - ~/.config/mc
  - ~/.config/nvim
- name: symlink dotfiles
  file:
    state: link
    dest: '{{ item.dest }}'
    src: '{{ item.src }}'
  loop:
  - { dest: ~/.alacritty.toml, src: ~/.dotfiles/alacritty/.alacritty.toml }
  - { dest: ~/.gitconfig, src: ~/.dotfiles/git/.gitconfig }
  - { dest: ~/.gitign, src: ~/.dotfiles/git/.gitign }
  - { dest: ~/.tmux.conf, src: ~/.dotfiles/tmux/.tmux.conf }
  - { dest: ~/.tmux-top, src: ~/.dotfiles/tmux/.tmux-top }
  - { dest: ~/.vimrc, src: ~/.dotfiles/vim/.vimrc }
  - { dest: ~/.zshrc, src: ~/.dotfiles/zsh/.zshrc }
  - { dest: ~/.zsh-theme, src: ~/.dotfiles/zsh/.zsh-theme }
  - { dest: ~/.config/pretty-git-prompt.yml, src: ~/.dotfiles/p-g-p/.config/pretty-git-prompt.yml }
  - { dest: ~/.config/mc/mc.keymap, src: ~/.dotfiles/mc/mc.keymap }
  - { dest: ~/.config/mc/ini, src: ~/.dotfiles/mc/ini }
  - { dest: ~/.config/mc/panels.ini, src: ~/.dotfiles/mc/panels.ini }
  - { dest: ~/.config/nvim/init.lua, src: ~/.dotfiles/nvim/init.lua }
  - { dest: ~/.config/nvim/lua, src: ~/.dotfiles/nvim/lua }
- name: symlink git commit template
  file:
    state: link
    dest: ~/.git-template
    src: ~/.dotfiles/git/.git-template
  when: git_template is not defined
- name: check if git commit template is a symlink
  stat:
    path: ~/.git-template
  register: git_template_stat
  when: git_template is defined
- name: remove git commit template symlink
  file:
    path: ~/.git-template
    state: absent
  when:
  - git_template is defined
  - git_template_stat.stat.exists
  - git_template_stat.stat.islnk
- name: generate git commit template for hosts that differ from the dotfiles default
  template:
    src: git-template
    dest: ~/.git-template
  when: git_template is defined
# TODO: services role: open firewall 60001 port for mosh, change ssh port, disable root login
