---
- name: ensure ~/.local/bin exists
  file:
    state: directory
    path: ~/.local/bin
- name: download pretty-git-prompt binary
  get_url:
    url: https://github.com/TomasTomecek/pretty-git-prompt/releases/download/0.1.2/pretty-git-prompt-0.1.2-x86_64-unknown-linux-gnu
    dest: ~/.local/bin/pretty-git-prompt
    mode: 0511
