---
- name: ensure ~/.local/bin exists
  file:
    state: directory
    path: ~/.local/bin
# FIXME: if x86_64
- name: download pretty-git-prompt binary
  get_url:
    url: https://github.com/TomasTomecek/pretty-git-prompt/releases/download/0.1.2/pretty-git-prompt-0.1.2-x86_64-unknown-linux-gnu
    dest: ~/.local/bin/pretty-git-prompt
    mode: 0511
# TODO: provide releases
# - name: download tmux-top binary
#   get_url:
#     url: https://github.com/TomasTomecek/tmux-top/releases/download/...
#     dest: ~/.local/bin/tmux-top
#     mode: 0511
