---
- name: copy unit files
  template:
    src: sync-dotfiles.service
    dest: ~/.config/systemd/user/
- name: copy timer unit
  template:
    src: sync-dotfiles.timer
    dest: ~/.config/systemd/user/
- name: enable timer unit
  systemd:
    name: sync-dotfiles.timer
    enabled: true
    user: true
    daemon_reload: yes
- name: enable sync-dotfiles unit
  systemd:
    name: sync-dotfiles.service
    enabled: true
    state: started
    user: true
    daemon_reload: yes
