---
- name: pull this repo; WTF, right?
  git:
    dest: '{{ playbook_dir }}'
    repo: git@github.com:TomasTomecek/bubo-bubo
    update: yes
    track_submodules: yes
    recursive: yes
    accept_hostkey: yes
  ignore_errors: yes
- name: copy unit files
  template:
    src: sync-configuration.service
    dest: ~/.config/systemd/user/
- name: copy timer unit
  template:
    src: sync-configuration.timer
    dest: ~/.config/systemd/user/
# TODO: make 'user' configurable
- name: enable sync-configuration unit
  systemd:
    name: sync-configuration.service
    enabled: true
    state: reloaded
    user: true
  ignore_errors: yes
- name: enable timer unit
  systemd:
    name: sync-configuration.timer
    enabled: true
    user: true
    state: started
  ignore_errors: yes
