---
- name: pull this repo; WTF, right?
  git:
    dest: '{{ playbook_dir }}'
    repo: git@github.com:TomasTomecek/bubo-bubo
    update: yes
- name: copy unit files
  template:
    src: sync-configuration.service
    dest: ~/.config/systemd/user/
- name: copy timer unit
  template:
    src: sync-configuration.timer
    dest: ~/.config/systemd/user/
- name: enable timer unit
  systemd:
    name: sync-configuration.timer
    enabled: true
    user: true
    daemon_reload: yes
- name: enable sync-configuration unit
  systemd:
    name: sync-configuration.service
    enabled: true
    state: started
    user: true
    daemon_reload: yes
