---
- name: pull dotfiles first
  git:
    repo: https://github.com/TomasTomecek/dotfiles
    dest: ~/.dotfiles
    update: yes
- name: copy unit files
  template:
    src: sync-configuration.service
    dest: ~/.config/systemd/user/
- name: copy timer unit
  template:
    src: sync-configuration.timer
    dest: ~/.config/systemd/user/
- name: enable timer unit
  systemd:
    name: sync-configuration.timer
    enabled: true
    user: true
    daemon_reload: yes
- name: enable sync-configuration unit
  systemd:
    name: sync-configuration.service
    enabled: true
    state: started
    user: true
    daemon_reload: yes
