---
- name: Start and enable timesyncd.
  systemd:
    name: systemd-timesyncd
    state: started
    enabled: true
  become: true
- name: Set timezone to Bratislava.
  command: timedatectl set-timezone Europe/Bratislava
  become: true
- name: set hostname to {{ target }}
  hostname:
    name: '{{ target }}'
  become: true
- name: Disable PC Speaker - the loud beeping PITA
  copy:
    content: "blacklist pcspkr\n"
    dest: /etc/modprobe.d/pcspkr-blacklist.conf
  become: true
